### ISSUE TITLE
Links in footer are not centrally aligned on Safari

### ISSUE THREAD

**Issue by alexandermendes** [alexandermendes/BL-pybossa-theme#30]
Could be this bit of CSS that isn't working

``` css
.hcenter{justify-content:center;-ms-flex-pack:center;align-items:center;-webkit-align-items:center;-ms-flex-align:center}
```
